### PR TITLE
Fix declaration compatibility issue (bug #6).

### PR DESCRIPTION
**Pull request by kabalin**
Patch to fix issue #6.

### CODE REVIEW

**Comment by kabalin** [comment]
OK, this issue has been created automatically as a result of pull request, this is essentially a duplicate of #6.

**Comment by kabalin** [comment]
OK, added nulls for $flags parameter to make it compatible with 2.5, thanks Aaron for pointing this out.

**Comment by agwells** [comment]
Merged, cheers!

**Comment by azrek** [comment]
Hi,

I think this has caused in an issue in 2.5.  The changes that were applied were only relevant in 2.6.

In 2.5, the declaration for the lock and unlock functions in locallib.php should be:

public function lock(stdClass $submission) {

and

public function unlock(stdClass $submission) {

The  extended abstract class 'assign_submission_plugin' has this definition for the lock and lock functions:

```
public function lock(stdClass $submission) {
}
public function unlock(stdClass $submission) {
}
```

I'm currently getting the following error in 2.5:

Strict standards: Declaration of assign_submission_mahara::lock() should be compatible with that of assign_submission_plugin::lock() in /var/www/moodle/moodle/mod/assign/submission/mahara/locallib.php on line 811 Call Stack: 0.0025 659816 1. {main}() /var/www/moodle/moodle/mod/assign/view.php:0 0.2601 56011744 2. assign->__construct(???, ???, ???) /var/www/moodle/moodle/mod/assign/view.php:46 0.2601 56012208 3. assign->load_plugins(???) /var/www/moodle/moodle/mod/assign/locallib.php:141 Strict standards: Declaration of assign_submission_mahara::unlock() should be compatible with that of assign_submission_plugin::unlock() in /var/www/moodle/moodle/mod/assign/submission/mahara/locallib.php on line 811 Call Stack: 0.0025 659816 1. {main}() /var/www/moodle/moodle/mod/assign/view.php:0 0.2601 56011744 2. assign->__construct(???, ???, ???) /var/www/moodle/moodle/mod/assign/view.php:46 0.2601 56012208 3. assign->load_plugins(???) /var/www/moodle/moodle/mod/assign/locallib.php:141

Cheers.

**Comment by agwells** [comment]
Hi azrek,

Good point. I've pushed a patch to fix that in the moodle25 branch.

We've also moved the "official" repo for this plugin to the MaharaProject repo, so please try it out there: https://github.com/catalyst/moodle-assignsubmission-mahara/pull/7

Cheers,
Aaron

**Pull request merged**
